spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/db_input_output
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: smtp@mailtrap.io
#TODO ENV VAR AQUI
    password: 088a0b79126ea57cc8170828e941191b

    properties:
      mail:
        smtp:
          auth: LOGIN
          starttls:
          enable: true
  
mail: 
  recipient: rafael@roseno.dev 
    
aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
  region: sa-east-1
  s3:
    bucketName: soat-storage
  cognito:
    userPoolId: sa-east-1_ItVS6S47N
    jwkSetUri: https://cognito-idp.sa-east-1.amazonaws.com/sa-east-1_ItVS6S47N/.well-known/jwks.json
    client:
      name: input-output-cognito
      id: 1muhaermpvh2evqurl4fopct2f
      secret: ${AWS_COGNITO_CLIENT_SECRET}
  sqs:
    queueName: soat_new_update_file
    queueUrl: "https://sqs.sa-east-1.amazonaws.com/588738607552/soat_new_update_file"
    
