spring:
  profiles:
    active: ${CURRENT_ENV:dev}
    
  application:
    name: service-input-output
   
   
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: "Service Input-Outpu API"
    description: "API para o controle do processamento de vídeos."
    version: "1.0"
